defaults: &defaults
  javascript:
    log_level: 0
  use_cdn: true

development:
  <<: *defaults
  use_cdn: false
  javascript:
    log_level: 3

production:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults
  use_cdn: false
